version: "3.7"

networks:
  net:
    attachable: true

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - net
  app:
    image: tiny-url:latest
    build: .
    environment:
      - REDIS_HOST=redis
    networks:
      - net
